// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankSistem.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20211215195910_DatabaseCreation")]
    partial class DatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdAccount");

                    b.Property<decimal>("Balance")
                        .HasColumnType("Money");

                    b.Property<Guid>("IdBank")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCardOwner")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdBank");

                    b.HasIndex("IdCardOwner");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Entities.Models.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdBank");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Entities.Models.BankBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdBankBranch");

                    b.Property<Guid>("IdBank")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTown")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdBank");

                    b.HasIndex("IdTown");

                    b.ToTable("BankBranches");
                });

            modelBuilder.Entity("Entities.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCard");

                    b.Property<decimal>("Balance")
                        .HasColumnType("Money");

                    b.Property<Guid>("IdAccount")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdAccount");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Entities.Models.CardOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCardOwner");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("CardOwners");
                });

            modelBuilder.Entity("Entities.Models.OwnerStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdOwnerStatus");

                    b.Property<Guid>("IdCardOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSocialStatus")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdCardOwner");

                    b.HasIndex("IdSocialStatus");

                    b.ToTable("OwnerStatuses");
                });

            modelBuilder.Entity("Entities.Models.SocialStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdSocialStatus");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("SocialStatuses");
                });

            modelBuilder.Entity("Entities.Models.Town", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdTown");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Towns");
                });

            modelBuilder.Entity("Entities.Models.Account", b =>
                {
                    b.HasOne("Entities.Models.Bank", "Bank")
                        .WithMany("Accounts")
                        .HasForeignKey("IdBank")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.CardOwner", "CardOwner")
                        .WithMany("Accounts")
                        .HasForeignKey("IdCardOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("CardOwner");
                });

            modelBuilder.Entity("Entities.Models.BankBranch", b =>
                {
                    b.HasOne("Entities.Models.Bank", "Bank")
                        .WithMany("BankBranches")
                        .HasForeignKey("IdBank")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Town", "Town")
                        .WithMany("BankBranches")
                        .HasForeignKey("IdTown")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Town");
                });

            modelBuilder.Entity("Entities.Models.Card", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("Cards")
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Entities.Models.OwnerStatus", b =>
                {
                    b.HasOne("Entities.Models.CardOwner", "CardOwner")
                        .WithMany("OwnerStatuses")
                        .HasForeignKey("IdCardOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.SocialStatus", "SocialStatus")
                        .WithMany("OwnerStatuses")
                        .HasForeignKey("IdSocialStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardOwner");

                    b.Navigation("SocialStatus");
                });

            modelBuilder.Entity("Entities.Models.Account", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Entities.Models.Bank", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("BankBranches");
                });

            modelBuilder.Entity("Entities.Models.CardOwner", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("OwnerStatuses");
                });

            modelBuilder.Entity("Entities.Models.SocialStatus", b =>
                {
                    b.Navigation("OwnerStatuses");
                });

            modelBuilder.Entity("Entities.Models.Town", b =>
                {
                    b.Navigation("BankBranches");
                });
#pragma warning restore 612, 618
        }
    }
}
